apiVersion: v1
kind: Secret
metadata:
  name: auth-db-creds
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: password
  PGADMIN_DEFAULT_EMAIL: admin@local
  PGADMIN_DEFAULT_PASSWORD: pgadmin
